# Language info
language = "English"
language_en = "English"
author = "Valer100"

# Main window
see_open_source_licenses = "See open source licenses"
settings = "Settings"
volume = "Volume"
label = "Label"
icon = "Icon"
default_icon = "Default icon"
choose_icon = "Choose icon"
create_icon_from_image = "Create icon from image"
choose_image = "Choose an image"
images = "Images"
apply_changes = "Apply changes"
remove_customizations = "Remove customizations"
remove_customizations_message = "Are you sure? Every single customization made to your volume through the \"autorun.inf\" file will be removed."
local_disk = "Local Disk"
additional_options = "Additional options"
hide_autorun = "Hide autorun.inf file"
hide_vl_icon = "Hide vl_icon folder"
backup_existing_autorun = "Backup autorun.inf file (if it already exists)"

# Messages
done = "Done"
operation_complete = "The volume's information were changed.\n\nIf the volume is on a removable drive, unplug the drive and plug it back into your computer for the changes to take effect. If it isn't, the changes will take effect the next time you log in."
permission_denied = "Permission denied"
read_only_volume_message = "The selected volume is read-only"
volume_not_accessible = "Volume not accessible"
volume_not_accessible_message = "The selected volume is not accessible."
error = "Error"
failure_message = "Failed to change the volume's information.\n\n"
missing_icon_file = "The copied icon file is missing."
unicode_not_supported = "Unicode characters are not supported. Make sure the label doesn't contain Unicode characters and try again."

# Other
open_source_licenses = "Open source licenses"
change_language = "Change language"
change_theme = "Change theme"
light_theme = "Light theme"
dark_theme = "Dark theme"
lang_system_default = "System default"
ok = "OK"
cancel = "Cancel"