# Language info
language = "Română"
language_en = "Romanian"
author = "Valer100"

# Main window
see_open_source_licenses = "Vezi licențele open source"
settings = "Setări"
volume = "Volum"
label = "Etichetă"
icon = "Pictogramă"
default_icon = "Pictogramă implicită"
choose_icon = "Alege pictograma"
create_icon_from_image = "Creează pictogramă din imagine"
choose_image = "Alege o imagine"
image = "Imagini"
apply_changes = "Aplică modificările"
remove_customizations = "Elimină personalizările"
remove_customizations_message = "Ești sigur(ă)? Toate personalizările făcute volumului tău prin fișierul \"autorun.inf\" vor fi eliminate."
local_disk = "Disc local"

# Messages
done = "Gata"
operation_complete = "Informațiile volumului au fost modificate. Dacă volumul se află pe o unitate amovibilă, deconectează unitatea și conecteaz-o înapoi la calculator pentru ca modificările să aibă efect. Dacă nu, modificările vor avea efect când te vei conecta data viitoare."
permission_denied = "Permisiune refuzată"
read_only_volume_message = "Volumul selectat poate fi doar citit."
volume_not_accessible = "Volum inaccesibil"
volume_not_accessible_message = "Volumul selectat este inaccesibil."
error = "Eroare"
failure_message = "Nu s-au putut modifica informațiile volumului.\n\n"
missing_icon_file = "Fișierul pictogramei copiate lipsește."

# Other
open_source_licenses = "Licențe open source"
change_language = "Schimbă limba"
change_theme = "Schimbă tema"
light_theme = "Temă luminoasă"
dark_theme = "Temă întunecată"
lang_system_default = "Prestabilită de sistem"
ok = "OK"
cancel = "Anulare"